import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,RecaptchaVerifier,signInWithPhoneNumber,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,collection,getDocs}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";import{FIREBASE_CONFIG}from"./firebase-config.js";
const $=id=>document.getElementById(id),app=initializeApp(FIREBASE_CONFIG),auth=getAuth(app),db=getFirestore(app);let confirmation=null,captcha=null;
const fallback=[["computer-fundamentals","Computer Fundamentals","Computer"],["ms-word","MS Word","Office"],["ms-excel","MS Excel","Office"],["ms-powerpoint","MS PowerPoint","Office"],["computer-application","Computer Application","Computer"],["html","HTML","Web Development"],["css","CSS","Web Development"],["javascript","JavaScript","Programming"],["python","Python","Programming"],["java","Java","Programming"],["c","C","Programming"],["cpp","C++","Programming"],["networks","Networks","Networking"],["cybersecurity","Cybersecurity","Security"]];
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")}function esc(v){return String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
$("sendOtp").onclick=async()=>{let p=$("phone").value.trim();if(!/^\+\d{8,15}$/.test(p))return $("authStatus").textContent="Use +91XXXXXXXXXX format.";try{if(!captcha)captcha=new RecaptchaVerifier(auth,"recaptcha-container",{size:"invisible"});confirmation=await signInWithPhoneNumber(auth,p,captcha);$("otpArea").classList.remove("hidden");$("authStatus").textContent="OTP sent."}catch(e){$("authStatus").textContent=e.message}};
$("verifyOtp").onclick=async()=>{try{if(!confirmation)throw Error("Request OTP first.");await confirmation.confirm($("otp").value.trim())}catch(e){$("authStatus").textContent=e.message}};
$("logout").onclick=()=>signOut(auth);$("backHome").onclick=()=>show("home");onAuthStateChanged(auth,u=>{if(u){show("home");loadCourses()}else show("login")});
async function loadCourses(){let box=$("courses");box.innerHTML="<div class=card>Loading…</div>";try{let s=await getDocs(collection(db,"courses")),rows=s.empty?fallback.map(x=>({id:x[0],name:x[1],category:x[2]})):s.docs.map(d=>({id:d.id,...d.data()}));box.innerHTML="";rows.forEach(c=>{let b=document.createElement("button");b.className="course";b.innerHTML='<span class="badge">'+esc((c.name||c.id).slice(0,2).toUpperCase())+'</span><span><h3>'+esc(c.name||c.id)+'</h3><p>'+esc(c.category||"Course")+'</p></span>';b.onclick=()=>openCourse(c.id,c);box.appendChild(b)})}catch(e){box.innerHTML="<div class=card>Firestore connection failed. Check config/rules.</div>"}}
async function openCourse(id,c){show("course");$("courseHeader").innerHTML="<small>"+esc(c.category||"Course")+"</small><h2>"+esc(c.name||id)+"</h2>";let box=$("courseContent");box.innerHTML="<div class=card>Loading…</div>";try{let s=await getDocs(collection(db,"courses",id,"semesters"));if(s.empty){box.innerHTML="<div class=card>No semesters added yet.</div>";return}box.innerHTML="";for(let sem of s.docs){let w=document.createElement("div");w.className="lesson";w.innerHTML="<b>"+esc(sem.data().name||sem.id)+"</b><p>Semester</p>";let ch=await getDocs(collection(db,"courses",id,"semesters",sem.id,"chapters"));ch.forEach(x=>{let r=document.createElement("p");r.textContent=x.data().name||x.id;w.appendChild(r)});box.appendChild(w)}}catch(e){box.innerHTML="<div class=card>Could not load structure.</div>"}}
